# Generated by Django 3.1.3 on 2020-11-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название видео'),
        ),
    ]
