# Generated by Django 3.1.3 on 2020-11-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201125_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.ImageField(upload_to='videos/posters', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/videos/', verbose_name='Видео'),
        ),
    ]
