# Generated by Django 3.1.5 on 2021-02-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_channel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='image',
            new_name='logo',
        ),
    ]
