# Generated by Django 3.1.5 on 2021-02-22 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20210221_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rated_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, давшие оценку виде'),
        ),
    ]
