# Generated by Django 3.1.5 on 2021-02-22 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_video_rated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='rated_by',
        ),
        migrations.AddField(
            model_name='video',
            name='disliked_by',
            field=models.ManyToManyField(related_name='likes_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие видео дизлайк'),
        ),
        migrations.AddField(
            model_name='video',
            name='liked_by',
            field=models.ManyToManyField(related_name='disliked_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие видео лайк'),
        ),
    ]
