# Generated by Django 3.1.5 on 2021-02-22 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20210222_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие видео дизлайк'),
        ),
        migrations.AlterField(
            model_name='video',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие видео лайк'),
        ),
    ]
