# Generated by Django 3.1.7 on 2021-03-08 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20210222_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, подписавшиеся на канал'),
        ),
    ]
